@startuml
participant ArticleController as servlet
participant ArticleDAO as dao
participant HttpServletRequest as req
participant HttpServletResponse as resp
participant SellPage

note over servlet
    POST /insertArticle
    articleName -> articleName
    articleDesc -> articleDesc
    articlePrice -> articlePrice
    articleImage -> articleImage
end note

-> servlet ++ : doPost

servlet -> req ++ : getSession().getAttribute("user")
req -> servlet -- : session

alt any of the params are wrong or missing
    servlet -> req : setAttribute("$$__args__$$", new SellPageArgs(ERROR_DATA_FORMAT, new ArticleData(valid params)))
    servlet -> resp : forward to /sell
else
    servlet -> dao : insertArticle(articleName, articleDesc, imageStream, articlePrice, session.id())
    alt query error
        servlet -> req : setAttribute("$$__args__$$", new SellPageArgs(ERROR_QUERY, new ArticleData(articleName, articleDesc, articlePrice)))
        servlet -> resp : forward to /sell
    else insertion successful
        servlet -> SellPage --++ : REDIRECT /sell
    end
end

@enduml